- hosts: all
  become: true
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config
  tasks:
    - name: delete old deployment
      command: kubectl delete -f /home/ubuntu/Deployment.yml
    - name: delete old service
      command: kubectl delete -f /home/ubuntu/Service.yml

