kind: Deployment
apiVersion: apps/v1
metadata:
   name: phatcao99
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: phatcao99
   template:
      metadata:
        labels:
          app: phatcao99
      spec:
       containers:
        - name: phatcao99
          image: phatcao99/pipeline-demo
          imagePullPolicy: Always
          ports:
          - containerPort: 80