kind: Service                             
apiVersion: v1
metadata:
  name: phatcao99
  labels:
    app: phatcao99
spec:
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31200
  selector:
    app: phatcao99
  type: nodePort
