kind: Service
apiVersion: v1
metadata:
  name: phatcao99
  labels:
    app: phatcao99
spec:
  ports:
    - port: 8080
      targetPort: 80
      # Remove nodePort
  selector:
    app: phatcao99
  type: LoadBalancer
